### ISSUE TITLE
Bad initial position method

### ISSUE THREAD

**Issue by krispya** [Ctrlmonster/r3f-koota-starter#1]
The `Sphere` component looks like this:
```js
export function Sphere({ entity }: { entity: Entity }) {
  // we only get initial position as prop – we won't re-render this component when the position changes! –
  // instead, a system will update the position imperatively. If we wanted to re-render we could
  // use the `useTrait` hook to get a reactive snapshot of the Position trait.
  const initPosition = useMemo(() => Object.values(entity.get(Position)) as Vector3Tuple, [entity]);
  const meshRef = useRef<Mesh>(null!);

  useEffect(() => {
    // add the ref to the mesh as a trait to the entity
    entity.add(MeshRef({ ref: meshRef.current }));
    return () => {
      entity.remove(MeshRef);
    };
  }, [entity]);

  return (
    <mesh position={initPosition} ref={meshRef} castShadow receiveShadow>
      <sphereGeometry args={[0.65, 18, 18]} />
      <meshStandardMaterial color={"gold"} />
    </mesh>
  );
}
```
And passes a memoized version of the position into the position prop on the `mesh` for the initial position and then after this the position is overwritten by a system imperatively. This is a common mistake. It mixes a controlled prop with mutation and bugs will appear if the component rerenders for any reason, including HMR.

If a prop is meant to be uncontrolled, ie mutated by a system, it should **never** be set via props on the JSX. Instead, the initial position should be set imperatively in an effect, or, if order is really important, imperatively in the ref callback. Likely what you want is to set all the initial properties and capture the ref in the ref callback so that all of this data will be set before any effects occur.

**Comment by krispya** [comment]
~~Also, `useEntityRef` will do all of this for you.~~

`useEntityRef` should handle this sort of situation for you but it generates an entity instead of letting you pass one in. I'll have to generalize this API.

**Comment by Ctrlmonster** [comment]
You're right, this would require the Component to be wrapped in a `memo` too / or use the React compiler (in which case I would prefer this for readability). But I'll change it to make sure there is no confusion.

**Comment by krispya** [comment]
FYI if you use the ref callback make sure you memoize it with `useCallback` as the ref callback will rerun every time the component rerenders if it finds a new function (arrow function for example).

In React 18 you cannot return a cleanup function but the ref will be passed in as `null` when a cleanup is happening so just test for null and run whatever cleanup you need.

**Comment by Ctrlmonster** [comment]
Ah that's good to know. I just removed the init position completely for the example as the mesh is picked up in the first frame anyway.
